# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phishing_backend_container
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - phishing_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: phishing_frontend_container
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - phishing_network

networks:
  phishing_network:
    driver: bridge